const object1 = {
    "Людина-павук: Додому шляху нема":["<a class='search_text' href='http://diploma/film.php?film=1'><br><b>Людина-павук: Додому шляху нема</b></br></a>","images/11.jpg"],
    "Бетмен":["<a class='search_text' href='http://diploma/film.php?film=2'><br><b>Бетмен</b></br></a>","images/22.jpg"],
    "Uncharted: Незвідане":["<a class='search_text' href='http://diploma/film.php?film=3'><br><b>Uncharted: Незвідане</b></br></a>","images/33.jpg"],
    "Інтерстеллар":["<a class='search_text' href='http://diploma/film.php?film=4'><br><b>Інтерстеллар</b></br></a>","images/44.jpg"],
    "Аватар 2":["<a class='search_text' href='http://diploma/film.php?film=5'><br><b>Аватар 2</b></br></a>","images/55.jpg"],
    "Месники: Війна нескінченності":["<a class='search_text' href='http://diploma/film.php?film=6'><br><b>Месники: Війна нескінченності</b></br></a>","images/66.jpg"],
    "Доктор Стрендж":["<a class='search_text' href='http://diploma/film.php?film=7'><br><b>Доктор Стрендж</b></br></a>","images/77.jpg"],
    "Чорний телефон":["<a class='search_text' href='http://diploma/film.php?film=8'><br><b>Чорний телефон</b></br></a>","images/88.jpg"],
    "Обігнати час":["<a class='search_text' href='http://diploma/film.php?film=10'><br><b>Обігнати час</b></br></a>","images/99.jpg"],
    "Мавка. Лісова пісня":["<a class='search_text' href='http://diploma/film.php?film=10'><br><b>Мавка. Лісова пісня</b></br></a>","images/100.jpg"],
    "Їжак Сонік 2":["<a class='search_text' href='http://diploma/film.php?film=11'><br><b>Їжак Сонік 2</b></br></a>","images/111.jpg"],
    "Довбуш":["<a class='search_text' href='http://diploma/film.php?film=12'><br><b>Довбуш</b></br></a>","images/122.jpg"],
    "Крик":["<a class='search_text' href='http://diploma/film.php?film=13'><br><b>Крик</b></br></a>","images/133.jpg"],
    "Варяг":["<a class='search_text' href='http://diploma/film.php?film=14'><br><b>Варяг</b></br></a>","images/144.jpg"],
    "Найманець":["<a class='search_text' href='http://diploma/film.php?film=15'><br><b>Найманець</b></br></a>","images/155.jpg"],
    "Фантастичні звірі: Таємниці Дамблдора":["<a class='search_text' href='http://diploma/film.php?film=16'><br><b>Фантастичні звірі: Таємниці Дамблдора</b></br></a>","images/166.jpg"],
    "Світ Юрського періоду: Домініон":["<a class='search_text' href='http://diploma/film.php?film=17'><br><b>Світ Юрського періоду: Домініон</b></br></a>","images/177.jpg"],
    "Найкращий стрілець: Меверік":["<a class='search_text' href='http://diploma/film.php?film=18'><br><b>Найкращий стрілець: Меверік</b></br></a>","images/188.jpg"],
    "Падіння Місяця":["<a class='search_text' href='http://diploma/film.php?film=19'><br><b>Падіння Місяця</b></br></a>","images/199.jpg"],
    "Операція 'Фортуна': Мистецтво перемагати":["<a class='search_text' href='http://diploma/film.php?film=20'><br><b>Операція 'Фортуна': Мистецтво перемагати</b></br></a>","images/200.jpg"],
};